#!/usr/bin/env node

/**
 * Renders docs/state-machine.md from the transition table that the running system enforces, then
 * fails if the committed file differs. Documentation that is generated from the same constant the
 * code reads cannot describe a lifecycle the code does not implement.
 *
 * Pass --write to regenerate.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT_PATH = resolve(repositoryRoot, 'docs/state-machine.md');
const BUILD_OUTPUT = resolve(repositoryRoot, 'packages/shared/dist/index.js');

async function loadTable() {
  try {
    return await import(`file://${BUILD_OUTPUT}`);
  } catch {
    process.stderr.write(
      `Could not import ${BUILD_OUTPUT}.\nRun "npm run build" first: this generator reads the compiled table so it cannot drift from what ships.\n`,
    );
    process.exit(1);
  }
}

function renderStatusTable(shared) {
  const rows = shared.PAYMENT_STATUSES.map((status) => {
    const terminal = shared.isTerminalPaymentStatus(status) ? 'yes' : 'no';
    const outgoing = shared.allowedTargetsFrom(status);
    const reachable = outgoing.length === 0 ? '-' : outgoing.join(', ');
    return `| \`${status}\` | ${terminal} | ${reachable} |`;
  });
  return ['| Status | Terminal | Can move to |', '| --- | --- | --- |', ...rows].join('\n');
}

function renderTransitionTable(shared) {
  const rows = shared.PAYMENT_TRANSITIONS.map(
    (edge, index) =>
      `| ${index + 1} | \`${edge.from}\` | \`${edge.to}\` | \`${edge.trigger}\` | ${edge.guard} |`,
  );
  return ['| # | From | To | Trigger | Guard |', '| --- | --- | --- | --- | --- |', ...rows].join(
    '\n',
  );
}

function renderDiagram(shared) {
  const edges = shared.PAYMENT_TRANSITIONS.map(
    (edge) => `    ${edge.from} --> ${edge.to} : ${edge.trigger}`,
  );
  return ['```mermaid', 'stateDiagram-v2', '    [*] --> pending', ...edges, '```'].join('\n');
}

function renderDocument(shared) {
  const statusCount = shared.PAYMENT_STATUSES.length;
  const edgeCount = shared.PAYMENT_TRANSITIONS.length;
  const orderedPairs = statusCount * statusCount;
  const distinctPairs = orderedPairs - statusCount;
  const rejectedPairs = distinctPairs - edgeCount;

  return `<!-- Generated by scripts/verify-docs.mjs. Do not edit by hand. -->

# Payment lifecycle

A payment holds one of ${statusCount} statuses. Exactly ${edgeCount} status-changing edges are
declared, in \`packages/shared/src/payment-transition-table.ts\`. That table is the single source of
truth: the API's state machine and this document are both generated from it, and CI fails if they
disagree.

Of the ${distinctPairs} ordered pairs of distinct statuses, ${edgeCount} are permitted and
${rejectedPairs} are rejected. The test suite enumerates the full Cartesian product rather than
sampling it, and the transition table and state machine are held at 100% coverage.

## Statuses

${renderStatusTable(shared)}

Every terminal status is genuinely terminal: no edge leaves one. A transfer that arrives against a
finished payment is recorded and reported, never applied. Resurrection edges out of terminal states
are the bug class that double-credits a merchant.

## Triggers

${shared.PAYMENT_TRIGGERS.map((trigger) => `- \`${trigger}\``).join('\n')}

## Transitions

${renderTransitionTable(shared)}

## Diagram

${renderDiagram(shared)}

## Decisions worth knowing

- **\`confirming\` cannot expire.** Once sufficient value is on chain, a timer firing is irrelevant.
  Expiring a funded payment because a clock advanced would be taking the customer's money.
- **\`partially_funded\` is separate from \`underpaid\`.** Keeping them apart is what removes any need
  for an \`underpaid -> completed\` edge: a top-up before expiry moves between non-terminal states,
  and after expiry the payment is finished.
- **There is no \`failed\` status.** A reverted ERC-20 transfer emits no Transfer event, so it is
  never observed and there is nothing to fail. Settlement failure lives in an orthogonal column that
  cannot corrupt a completed payment.
- **Multiple transfers are summed.** Aggregating credited transfers removes the need for an
  unresolved "multiple payments" status.
`;
}

async function main() {
  const shared = await loadTable();
  const rendered = renderDocument(shared);
  const shouldWrite = process.argv.includes('--write');

  if (shouldWrite) {
    await writeFile(OUTPUT_PATH, rendered, 'utf8');
    process.stdout.write(`Wrote ${OUTPUT_PATH}\n`);
    return;
  }

  let existing;
  try {
    existing = await readFile(OUTPUT_PATH, 'utf8');
  } catch {
    existing = null;
  }
  if (existing === rendered) {
    process.stdout.write('docs/state-machine.md matches the transition table.\n');
    return;
  }

  process.stderr.write(
    'docs/state-machine.md is out of date with packages/shared/src/payment-transition-table.ts.\nRun: npm run docs:generate\n',
  );
  process.exitCode = 1;
}

await main();
